param(
  [string]$Profile = "production"
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$androidSdk = Join-Path $repoRoot "android-sdk"
$cacheRoot = if ($env:KUANTO_BUILD_CACHE) {
  $env:KUANTO_BUILD_CACHE
} else {
  Join-Path ([System.IO.Path]::GetPathRoot($repoRoot)) "kuanto-build-cache"
}
$gradleHome = Join-Path $cacheRoot "gradle"
$easWorkingDir = Join-Path $cacheRoot "eas"
$androidDir = Join-Path $repoRoot "android"

if (-not (Test-Path -LiteralPath $androidSdk)) {
  throw "Local Android SDK not found at $androidSdk"
}

if (-not (Test-Path -LiteralPath $androidDir)) {
  throw "Android project not found at $androidDir"
}

New-Item -ItemType Directory -Force -Path $gradleHome, $easWorkingDir | Out-Null

$env:ANDROID_HOME = (Resolve-Path -LiteralPath $androidSdk).Path
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
$env:GRADLE_USER_HOME = (Resolve-Path -LiteralPath $gradleHome).Path
$env:EAS_LOCAL_BUILD_WORKINGDIR = (Resolve-Path -LiteralPath $easWorkingDir).Path
$env:NODE_ENV = if ($env:NODE_ENV) { $env:NODE_ENV } else { "production" }

$localPropertiesPath = Join-Path $androidDir "local.properties"
$sdkDirForGradle = $env:ANDROID_HOME -replace "\\", "/"
$cmakeDir = Join-Path $androidSdk "cmake\3.22.1"
$cmakeDirForGradle = if (Test-Path -LiteralPath $cmakeDir) {
  (Resolve-Path -LiteralPath $cmakeDir).Path -replace "\\", "/"
} else {
  $null
}
@(
  "# Generated by scripts/eas-build-android-local.ps1",
  "sdk.dir=$sdkDirForGradle"
  $(if ($cmakeDirForGradle) { "cmake.dir=$cmakeDirForGradle" })
) | Set-Content -LiteralPath $localPropertiesPath -Encoding ascii

if (Get-Command eas -ErrorAction SilentlyContinue) {
  if ($env:OS -eq "Windows_NT") {
    & (Join-Path $androidDir "gradlew.bat") -p $androidDir ":app:bundleRelease" --no-daemon --console plain --info
  } else {
    & eas build --local -p android --profile $Profile
  }
} else {
  if ($env:OS -eq "Windows_NT") {
    & (Join-Path $androidDir "gradlew.bat") -p $androidDir ":app:bundleRelease" --no-daemon --console plain --info
  } else {
    & npx eas-cli build --local -p android --profile $Profile
  }
}
